USP/Controllers/AddEmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using USP.Models;
using USP.ViewModels;

namespace USP.Controllers
{
    public class AddEmployeeController : Controller
    {
        private EmployeeContext db;

        public AddEmployeeController(EmployeeContext context)
        {
            db = context;
        }

        [Authorize]
        public IActionResult Index()
        {
            return PartialView();
        }

        [HttpPost]
        [Authorize]
        public IActionResult Create(EmployeeModel employeeModel)
        {
            db.InsertEmployee(employeeModel);
            return RedirectToAction("Index", "EmployeeList");
        }
    }
}

USP/Views/AddEmployee/Index.cshtml
@model USP.ViewModels.EmployeeModel

<html>
<head>
    <meta charset="UTF-8">
    <title>Добавление сотрудника</title>
    <link href="~/css/css.css" rel="stylesheet">
</head>
<body>
    <form asp-action="Create" asp-controller="AddEmployee" asp-anti-forgery="true">
        <div>
            <fieldset>
                <legend id="label" style="font-size: 18px;">Паспортные данные</legend>
                <div id="passport">
                    <div id="col1">
                        <label asp-for="FirstName">Имя</label><br>
                        <input asp-for="FirstName" type="text"><br>
                        <span asp-validation-for="FirstName" />

                        <label asp-for="LastName">Фамилия</label><br>
                        <input asp-for="LastName" type="text"><br>
                        <span asp-validation-for="LastName" />

                        <label asp-for="MiddleName">Отчество</label><br>
                        <input asp-for="MiddleName" type="text"><br>
                        <span asp-validation-for="MiddleName" />
                    </div>
                </div>
            </fieldset>
        </div>
        <input id="buttom_creation" type="submit" name="creation_buttom" value="Создать">
    </form>
</body>
</html>